matrix:
  include:
    - os: linux
      language: python

services:
  - xvfb
  - mysql

env:
  - MYSQL_CODE_TIME_DB_NAME=codetime_db MYSQL_CODE_TIME_USER=travis MYSQL_CODE_TIME_PASSWORD='' MYSQL_CODE_TIME_HOST='127.0.0.1' MYSQL_CODE_TIME_CONNECTION_PORT=3306 CODE_TIME_SECRET_KEY=Sample

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
  - pip install flake8==3.5
  - sh travis.sh bootstrap
  - pip install -r code/codetime_server/requirements.txt

before_script:
  - mysql -e 'create database codetime_db;'
script:
  - flake8 --max-line-length=200
  - sh travis.sh run_tests
  - cd code/codetime_server/
  - coverage run --source='.' --omit=*sgi*,*apps* manage.py test codetime
  - coverage report

