language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
services:
  - xvfb
before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install flake8==3.5
  - pip install black
  - /bin/sh sbin/travis.sh bootstrap
  - /bin/sh sbin/travis.sh install_color_scheme_unit
  - if ["$PCINSTALL" == true]; then /bin/sh sbin/travis.sh install_package_control; fi
# command to run tests
script:
  - flake8 --statistics
  - /bin/sh sbin/travis.sh run_tests --coverage
  - python -m pytest